[package]
  cjc-version = "1.0.3"
  name = "epub"
  description = "EPUB parser library for Cangjie"
  version = "0.1.0"
  target-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  archive = { path = "../archive" }